# -*- coding: utf-8 -*-
"""galleta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2nrzBcIQHWqKAVbr1_tySegfM1npFpb
"""

import streamlit as st
import random
from datetime import datetime


st.image("UNRC.png", caption="Universidad Nacional Rosario Castellanos", width=300)

# Configuración de la página
st.set_page_config(page_title="Galletitas Financieras", page_icon="💰", layout="centered")

# Título principal
st.title("🥠 Galletitas Financieras 💰")
st.write("Cada clic revela un consejo financiero para mejorar tus hábitos de ahorro e inversión.")

# Lista de mensajes de buenos hábitos financieros
mensajes = [
    "💡 Ahorra primero, gasta después.",
    "📊 Lleva un registro mensual de tus ingresos y gastos.",
    "💰 Invierte en instrumentos que entiendas.",
    "🧾 Evita las deudas que no generen valor.",
    "🎯 Define metas financieras claras y medibles (sé realista).",
    "🏦 Aprovecha el interés compuesto: el tiempo es tu mejor aliado.",
    "💳 No gastes más de lo que ganas, aunque tengas crédito disponible.",
    "🪙 Separa un 10% de tu ingreso para emergencias.",
    "📚 La educación financiera es la mejor inversión.",
    "🏡 Piensa en el futuro: planifica tu retiro desde hoy.",
    "🧘‍♂️ La estabilidad financiera también es bienestar emocional.",
    "🌱 Cada pequeño ahorro es una semilla para tu libertad financiera.",
    "🔍 Antes de invertir, compara rendimientos y riesgos.",
    "🕐 Sé constante: la disciplina vence al impulso.",
    "📈 Diversifica tus inversiones, no pongas todos los huevos en la misma canasta.",
    "🧘‍♂️ Evita las pesadillas financieras, sé diciplinado financieramente.",
    "📊 El ahorro tiene un propósito, visualízalo para que sea una realidad.",
    "📊 Identifica tus gastos hormiga, evitandolos se convitirán en inversión.",
    "💳 El crédito puede ser un aliado, pero se puede comvertir en tu dolor de cabeza.",
    "💳 Si tienes problemas de compras compulsivas, evita las tarjetas de crédito.",
    "💰 De cafecito en cafecito, se nos va el dinerito.",
    "💰 Carga contigo siempre una fruta, agua y un termo de café, tu bolsillo te lo agradecerá.",
    "🔍 La información disuelve la emoción (conoce tus ingresos y gastos).",
    "📊 Cuando inviertes en la Bolsa, la paciencia es mejor que la inteligencia.",
    
]

# Botón para obtener una galletita
if st.button("🍪 Romper una galletita"):
    mensaje = random.choice(mensajes)
    st.success(mensaje)
    st.caption(f"{datetime.now().strftime('%d/%m/%Y, %H:%M:%S')}")

# Pie de página
st.markdown("---")

st.title("3ra. Emisión de las Jornadas Financieras en la UNRC")

st.caption("Licenciatura en Contaduría y Finanzas | Univeridad NacionalRosario Castellanos")
